# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yhnoh

plugins:
  - serverless-offline
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: hello-world
# "service" is the name of this project. This will also be added to your AWS resource names.
service: hello-world

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
